---
# https://eengstrom.github.io/musings/generate-non-contiguous-subuid-subgid-maps-for-rootless-podman

- name: Get user infos
  getent:
    database: passwd
    key: "{{ subid_user }}"

- name: Set subuids
  ansible.builtin.lineinfile:
    path: "/etc/subuid"
    regexp: "{{ subid_user }}"
    line: "{{ subid_user }}:{{ getent_passwd[subid_user].1 | int | bitwise_shift_left(subuid_bitshift) }}:65536"
    backup: true
    create: true
    mode: 0644
    owner: root
    group: root


- name: Set subgids
  ansible.builtin.lineinfile:
    path: "/etc/subgid"
    regexp: "{{ subid_user }}"
    line: "{{ subid_user }}:{{ getent_passwd[subid_user].2 | int | bitwise_shift_left(subgid_bitshift) }}:65536"
    backup: true
    create: true
    mode: 0644
    owner: root
    group: root
